export const TEMPLATE_PLACEHOLDER = {
    TODAY: '{%TODAY%}',
    TOMORROW: '{%TOMORROW%}',
    YESTERDAY: '{%YESTERDAY%}',
    NEXT_BUSINESS_DAY: '{%NEXT_BUSINESS_DAY%}',
    PREVIOUS_BUSINESS_DAY: '{%PREVIOUS_BUSINESS_DAY%}',
    TODAY_EVENTS: '{%TODAY_EVENTS%}',
    TOMORROW_EVENTS: '{%TOMORROW_EVENTS%}',
    YESTERDAY_EVENTS: '{%YESTERDAY_EVENTS%}',
    NEXT_BUSINESS_DAY_EVENTS: '{%NEXT_BUSINESS_DAY_EVENTS%}',
    PREVIOUS_BUSINESS_DAY_EVENTS: '{%PREVIOUS_BUSINESS_DAY_EVENTS%}',
} as const;

export type TemplatePlaceholder = TypeOfValues<typeof TEMPLATE_PLACEHOLDER>;
